
@port = 3000
@token = your_actual_jwt_or_api_token_here
@baseUrl = http://localhost:{{port}}

###
GET {{baseUrl}}/  HTTP/1.1

###
GET {{baseUrl}}/tasks  HTTP/1.1

###
GET {{baseUrl}}/tasks/68f119b6ff015cd3f5e94ce3  HTTP/1.1

###
POST {{baseUrl}}/tasks  HTTP/1.1
Content-Type: application/json
# Authorization: Bearer {{token}}

{
  "title": "Sweep the yard",
  "description": "Get up early in the morning at 6:30am and sweep the yard",
  //"status": "pending",
  //"priority": "low",
  "dueDate": "10-18-2025",
  "completed": false
}

###
PATCH {{baseUrl}}/tasks/68f11a40d3420be518a6b24c  HTTP/1.1
Content-Type: application/json
# Authorization: Bearer {{token}}

{
  "title": "Go home",
  "description": "Get up early in the morning at 6:30am and sweep the yard",
  //"status": "pending",
  //"priority": "low",
  "dueDate": "10-18-2025",
  "completed": false
}

###
DELETE {{baseUrl}}/tasks/68f11db93ac227079df1193f  HTTP/1.1
# Authorization: Bearer {{token}}